{
  pkgs,
  config,
  ...
}: {
  imports = [
    ./seafile.nix
    ./seafile-mysql.nix
    ./seafile-redis.nix
    ./notification-server.nix
  ];

  services.caddy.virtualHosts = {
    "seafile.simenmo.com" = {
      extraConfig = ''
        import acme-tls

        handle_path /notification* {
          rewrite * {uri}
          reverse_proxy localhost:8083
        }

        reverse_proxy localhost:8080
      '';
    };
  };

  clan.core.state.seafile = {
    folders = [
      "/files/seafile"
      "/files/seafile-mysql"
    ];
  };

  clan.core.vars.generators.seafile-mysql-password = {
    share = true; # same password used by both seafile and mysql containers
    files.password = {secret = true;};
    script = ''
      echo $(openssl rand -base64 32) > $out/password
    '';
    runtimeInputs = [pkgs.openssl];
  };

  clan.core.vars.generators.seafile-redis-password = {
    share = true;
    files.password = {secret = true;};
    script = ''
      echo $(openssl rand -hex 32) > $out/password
    '';
    runtimeInputs = [pkgs.openssl];
  };

  clan.core.vars.generators.seafile-jwt-private-key = {
    share = true;
    files.password = {secret = true;};
    script = ''
      echo $(openssl rand -base64 64) > $out/password
    '';
    runtimeInputs = [pkgs.openssl];
  };

  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}" = {
      allowedUDPPorts = [53];
      allowedTCPPorts = [80 443];
    };
  };

  virtualisation.oci-containers.backend = "podman";

  # Networks
  systemd.services."podman-network-seafile-net" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f seafile-net";
    };
    script = ''
      podman network inspect seafile-net || podman network create seafile-net
    '';
    partOf = ["podman-compose-seafile-root.target"];
    wantedBy = ["podman-compose-seafile-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-seafile-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
